$env:PYTHONUTF8 = "1"
$env:PYTORCH_CUDA_ALLOC_CONF = "expandable_segments:True"
$env:HTTP_PROXY = ""
$env:HTTPS_PROXY = ""
$env:ALL_PROXY = ""
$env:NO_PROXY = "*"
Set-Location "G:\AI\AuK"
"=== CONTROLLER START $(Get-Date) ===" | Out-File -Append -Encoding utf8 "G:\AI\_tmp\controller.log"
& ".venv\Scripts\python.exe" "local_train\auto_controller.py" *>> "G:\AI\_tmp\controller.log"
"=== CONTROLLER EXIT $LASTEXITCODE $(Get-Date) ===" | Out-File -Append -Encoding utf8 "G:\AI\_tmp\controller.log"
