$env:PYTHONUTF8 = "1"
$env:PYTORCH_CUDA_ALLOC_CONF = "expandable_segments:True"
$env:HTTP_PROXY = ""
$env:HTTPS_PROXY = ""
$env:ALL_PROXY = ""
$env:NO_PROXY = "*"
Set-Location "G:\AI\AuK"
"=== CONTROLLER S1 START $(Get-Date) ===" | Out-File -Append -Encoding utf8 "G:\AI\_tmp\controller_s1.log"
& ".venv\Scripts\python.exe" "local_train\auto_controller.py" --run_dir "local_train\run_ru_s1" --train_log "G:\AI\_tmp\train_s1.log" --enough_accent 8.5 --min_stop_update 3000 --max_updates 20000 --base_ckpt "G:\AI\AuK\local_train\run_ru\auk_ru_best.safetensors" --lora_r 32 --lora_alpha 64 *>> "G:\AI\_tmp\controller_s1.log"
"=== CONTROLLER S1 EXIT $LASTEXITCODE $(Get-Date) ===" | Out-File -Append -Encoding utf8 "G:\AI\_tmp\controller_s1.log"
